#数据库配置
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.29.130.240:3306/test?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=UTF8
  username: gitv_rd
  password: 1234.gitv_rd


spring:
  profiles:
    active: dev
## redis缓存配置
  cache:
    type: redis
  redis:
    database: 3
    host: 10.25.130.177
    password:
   # port: 6397
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #超时连接时长
    timeout: 10000
      #连接超时时间




####mybatis 配置
mybatis_config_file: mybatis-config.xml
mapper_path: /com/**/mapper/**.xml
entity_package: com.imooc.springbootmybatis.entity


###日志配置
logging:
  config: classpath:logback-boot.xml

